# Simple workflow for deploying static content to Pages
name: Deploy static content to Pages

on:
  # Runs on pushes to the default branch
  push:
    branches: ["main"]

  # Allows manual runs from the Actions tab
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Ensures only one deployment is active at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Specify the path to the directory containing index.html, e.g., `path: 'frontend'`
          path: './'  # Adjust if your files are not in the root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
